enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  'user/themes/quark/images/logo/INURB Logo Vetor.svg':
    name: 'INURB Logo Vetor.svg'
    type: image/svg+xml
    size: 3077
    path: 'user/themes/quark/images/logo/INURB Logo Vetor.svg'
