enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: false
sticky-footer: true
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/Lineage_OS_Logo.png:
    name: Lineage_OS_Logo.png
    type: image/png
    size: 108224
    path: user/themes/quark/images/logo/Lineage_OS_Logo.png
